"""Prometheus metrics configuration for the application.

This module sets up and configures Prometheus metrics for monitoring the application.
"""

from prometheus_client import Counter, Histogram, Gauge
from starlette_prometheus import metrics, PrometheusMiddleware

# Request metrics
http_requests_total = Counter("http_requests_total", "Total number of HTTP requests", ["method", "endpoint", "status"])

http_request_duration_seconds = Histogram(
    "http_request_duration_seconds", "HTTP request duration in seconds", ["method", "endpoint"]
)

# Database metrics
db_connections = Gauge("db_connections", "Number of active database connections")

llm_inference_duration_seconds = Histogram(
    "llm_inference_duration_seconds",
    "Time spent processing LLM inference",
    ["model"],
    buckets=[0.1, 0.3, 0.5, 1.0, 2.0, 5.0],
)


llm_stream_duration_seconds = Histogram(
    "llm_stream_duration_seconds",
    "Time spent processing LLM stream inference",
    ["model"],
    buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0],
)

session_names_generated_total = Counter(
    "session_names_generated_total",
    "Total session names generated by the LLM",
    ["status"],  # "success" | "error"
)

trace_span_total = Counter("trace_span_total", "Completed trace spans", ["span", "status"])
trace_span_duration_seconds = Histogram(
    "trace_span_duration_seconds",
    "Trace span duration",
    ["span", "status"],
)
llm_tokens_total = Counter("llm_tokens_total", "LLM token usage", ["model", "token_type"])
trace_errors_total = Counter("trace_errors_total", "Trace errors", ["span", "error_code"])


def record_trace_span(name, status, duration_ms, tokens, error, attributes) -> None:
    """Record low-cardinality aggregate metrics for one completed span."""
    trace_span_total.labels(span=name, status=status).inc()
    trace_span_duration_seconds.labels(span=name, status=status).observe(duration_ms / 1000)
    if error:
        trace_errors_total.labels(span=name, error_code=error.get("code", "unknown_error")).inc()
    if tokens:
        model = str(attributes.get("model", "unknown"))
        for token_type, value in tokens.to_dict().items():
            if value is not None:
                llm_tokens_total.labels(model=model, token_type=token_type).inc(value)


def setup_metrics(app):
    """Set up Prometheus metrics middleware and endpoints.

    Args:
        app: FastAPI application instance
    """
    # Add Prometheus middleware
    app.add_middleware(PrometheusMiddleware)

    # Add metrics endpoint
    app.add_route("/metrics", metrics)
